---
- name: datastore copy demo
  hosts: localhost
  gather_facts: false
  vars:
    mysrc: "iso/VMware-VMvisor-Installer-8.0U3-24022510.x86_64.iso"
    mydest: "VMware-VMvisor-Installer-8.0U3-24022510.x86_64.iso"
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  tasks:
    - name: copy file to datastore
      vsphere_copy:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        datastore: "{{ vcenter_datastore }}"
        src: "{{ mysrc }}"
        path: "{{ mydest }}"
